#!/bin/bash
# Display user information from /etc/passwd

while IFS=: read -r user _ uid _ gid desc home shell _; do
    echo "The user $user is part of the $gid gang, lives in $home, and rides $shell."
    echo "$uid's place is protected by the passcode PASSWORD. More info about the user here: USER ID INFO"
done < "/etc/passwd"

