#!/usr/bin/env bash
# Check information about the school file

FILE="school"

if [ -e "$FILE" ]; then
    # File exists
    echo "school file exists."

    if [ -s "$FILE" ]; then
        # File is not empty
        echo "school file is not empty."
    else
        # File is empty
        echo "school file is empty."
    fi

    if [ -f "$FILE" ]; then
        # File is a regular file
        echo "school is a regular file."
    fi
else
    # File does not exist
    echo "school file does not exist."
fi
